### ISSUE TITLE
audio.play() not working

### ISSUE THREAD

**Issue by boatbodger** [ksharindam/quartz-browser-qt5#10]
First, thanks for publishing this browser I think it may be just what I need.
I'm trying to move to quartz (away from chromium-browser) but find that the audio clips required by my (web, kiosk) application are not playing.
My javascript is:
function playSound(clipname){
	var audio = new Audio('clips/'+clipname);
	audio.play();
}
and I can see that the audio files are being served - just that no sound is produced.
Other applications play sound on the platform fine.
any ideas on how I can debug this?
Page is served by node.js, but I suspect that makes no difference.

**Comment by ksharindam** [comment]
At first check if the audio works in other websites. Open youtube and play
a video. If video does not play, then probably gstreamer framework is not
installed. Install gstreamer.
 If video plays fine, then its a problem of javascript engine. Then I can
do nothing.
Webkit engine lacks many features.

**Comment by own3mall** [comment]
Similar to @boatbodger reported issue, but I cannot get `<audio>` tags to play at all when manipulated via JavaScript or directly by the user in the browser.  `<audio>` tags just do NOT work?  I can't get any audio output setting (ffplay or other commands) to play these sounds.  They only work if you go directly to the audio source in the browser by using the URL.

Here's a basic sample that demonstrates this problem (inspect the page source for the full source):

http://dinofly.com/audio_test.html

**Comment by own3mall** [comment]
Installing pulseaudio fixed my problem.

```
sudo apt-get install pulseaudio
sudo apt-get install gstreamer1.0-pulseaudio
```

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=40860&start=1550#p1578896

**Comment by ksharindam** [comment]
Now closing this issue
