### ISSUE TITLE
No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by horstmannmat** [ksharindam/quartz-browser-qt5#2]
[QtWebKit](https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5) got deprecated upstream in Qt 5.5 and removed in 5.6.
You may want to switch to PyQt5.[QtWebEngineWidgets](http://pyqt.sourceforge.net/Docs/PyQt5/introduction.html#module-PyQt5.QtWebEngineWidgets)

**Comment by ksharindam** [comment]
Which os are you using?
I use debian stable (stretch) based distribution. and in this distribution qtwebkit is available in pyqt5.
I will switch to qtwebengine when debian buster will be released as stable.

**Comment by horstmannmat** [comment]
I am using ubuntu18.04, I will switch to Debian, test it, and give you a feedback.

Thanks!

**Comment by ksharindam** [comment]
Ok, 
and thanks for testing

**Comment by horstmannmat** [comment]
It worked on Debian stretch, I was wondering if there is a way to do it headless, and/or, use a driver like gecko to work with selenium. 

Thank you for your attention and I await your answer.

**Comment by ksharindam** [comment]
This browser is based on QtWebkit, and qt can not be run without x11. I dont think that it is possible to make it headless. 
As you have said, It can be headless, if i use browser engine like gecko. But i dont think that there is python wrapper of gecko. It will take much more time and effort if I use other programming languages (such as c or c++)
