### ISSUE TITLE
Command line options?

### ISSUE THREAD

**Issue by gemueselasagne** [ksharindam/quartz-browser-qt5#3]
Hi!

Are there any command line options available? Like starting the browser in full screen mode right away?

Thanks for the great work!

**Comment by ksharindam** [comment]
No, there is no command  line options available

**Comment by ksharindam** [comment]
some commandline options like fullscreen can be easily added.

**Comment by gemueselasagne** [comment]
that'd be an awesome feature for usage as  kiosk-system or digital sinage

**Comment by ksharindam** [comment]
Ok, Then I will add command line options.
which options would you like to have?

**Comment by gemueselasagne** [comment]
That’s awesome! Check https://peter.sh/experiments/chromium-command-line-switches/ for a list of chromium command line options. 

This is on my wishlist: 

--kisok or --fullscreen
Full-screen/Kiosk mode with no controls. Maybe controls could even be fully disabled and not just hidden.

--noerrdialogs 
Suppresses all error dialogs when present.

**Comment by ksharindam** [comment]
Ok, i will add those two options.
Just wait for 2 days.

**Comment by gemueselasagne** [comment]
awesome

**Comment by ksharindam** [comment]
kiosk mode has been added.
You can launch it in kiosk mode using command line option --kiosk

**Comment by gemueselasagne** [comment]
That’s so cool! 👍🏻

**Comment by smartm0use** [comment]
Hello, how to use `--kiosk` option? If I add it I get a splash screen with Quartz logo instead of given website.

**Comment by ksharindam** [comment]
I will check it out

**Comment by ksharindam** [comment]
I have checked and It works fine.

**Comment by ksharindam** [comment]
If you want to open google.com, enter command...
`quartz --kiosk www.google.com`

**Comment by smartm0use** [comment]
Yes, it works, but what happens if you set the option at the end of the command?

` quartz http://www.google.com --kiosk`

**Comment by ksharindam** [comment]
Url must be at the end. This program parses commandline options poorly.
