### ISSUE TITLE
Quartz on Raspberry: No such file or directory: '/home/pi/.config/quartz-browser/'

### ISSUE THREAD

**Issue by smartm0use** [ksharindam/quartz-browser-qt5#6]
Hello,
I get the following error when I try to run Quartz on Raspbian (without install):

```
libEGL warning: DRI2: failed to authenticate
Traceback (most recent call last):
  File "./quartz", line 9, in <module>
    sys.exit(main())
  File "/home/pi/quartz-browser-qt5-master/quartz_browser/main.py", line 957, in main
    window = Main()
  File "/home/pi/quartz-browser-qt5-master/quartz_browser/main.py", line 51, in __init__
    os.mkdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.config/quartz-browser/'
```

**Comment by ksharindam** [comment]
I am going to fix this today

**Comment by smartm0use** [comment]
In the meanwhile I solved copying folder from another installation (on Ubuntu)

**Comment by ksharindam** [comment]
Are you using raspberry pi?

**Comment by smartm0use** [comment]
Yes, I'm on Raspberry 1 with latest Raspbian.

**Comment by ksharindam** [comment]
did you not have .config directory in /home/pi initially?

**Comment by smartm0use** [comment]
No, I hadn't. So the fix is to create that folder if it doesn't exist.

**Comment by ksharindam** [comment]
So, thats the problem. It does not create the whole path. and assumes that there is a .config directory.
I will fix this today.

**Comment by ksharindam** [comment]
It has been fixed. Delete or move .config directory somewhere and test. and let me know.

**Comment by smartm0use** [comment]
Worked! Thank you.
