### ISSUE TITLE
QtNetwork Error 99 : Host unreachable

### ISSUE THREAD

**Issue by smartm0use** [ksharindam/quartz-browser-qt5#7]
This happens if I try to open a website that is running on my local server.

`./quartz http://www.google.com` it works

`./quartz http://www.google.c` (wrong address) -> QtNetwork Error 3 : Host www.google.c not found

`./quartz http://192.168.0.100:1234` -> **QtNetwork Error 99 : Host unreachable**

What is wrong with a local address?

**Comment by ksharindam** [comment]
Are you sure that the local address is valid. I have tested with other local addresses and it works fine.

**Comment by smartm0use** [comment]
Sorry, my bad. Please delete this issue.
I rebooted router and it changed my IP :(
