### ISSUE TITLE
Kiosk mode doesn't work propertly

### ISSUE THREAD

**Issue by smartm0use** [ksharindam/quartz-browser-qt5#8]
Kiosk mode isn't working propertly since there is still a 1px head at the top of the screen.
Can you fix it?

**Comment by ksharindam** [comment]
That white line is due to widget spacing.
Does this really need fix?

**Comment by smartm0use** [comment]
I think it is important for having full kiosk mode.

**Comment by ksharindam** [comment]
Fixed, the top line has been removed now.
